# SPDX-FileCopyrightText: 2023 Beachgeek Enterprises
# SPDX-License-Identifier: Apache-2.0

version: '3'
volumes:
  psql:
services:
  psql:
    image: postgres:15.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change-me
    volumes:
      - psql:/var/lib/postgresql/data 
    ports:
      - 5432:5432